# Generated by Django 3.1.7 on 2021-03-28 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
