# Generated by Django 3.1.7 on 2021-03-28 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_maker', '0002_schemacolumn_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
